#ifndef __LED_MANAGER_H__
#define __LED_MANAGER_H__

#include <stdint.h>

#define LED_ERROR_SEND_DURATION_MS 100
#define LED_ERROR_DISCONNECTED_DURATION_MS 200
#define LED_ERROR_DEVICE_IS_DISABLED_DURATION_MS 500

#define LED_ERROR_HW_MAG_CONNECTION_FAILED_DURATION_MS 3000
#define LED_ERROR_CLOUD_FAILED_DURATION_MS 4000
#define LED_ERROR_DEVICE_DISABLED_DURATION_MS 5000
#define LED_ERROR_NOT_COMMISSIONED_DURATION_MS 6000
#define LED_ERROR_ICCID_DURATION_MS 10000
#define LED_ERROR_HW_ID_GET_DURATION_MS 12000

#define LED_SUCCESS_DURATION_MS 100
#define LED_SUCCESS_DEVICE_CONNECTING_DURATION_MS 1000
#define LED_SUCCESS_DEVICE_ENABLED_DURATION_MS 2000
#define LED_SUCCESS_CONNECTED_DURATION_MS 3000

#define LED_INFO_DURATION_MS 200

typedef enum
{
    LED_OFF = 0,
    LED_ON = 1,
} led_state_t;

typedef enum
{
    LED_NONE = 0,
    LED_INFO = 1,
    LED_SUCCESS = 2,
    LED_ERROR = 3,
} led_type_t;

void led_manager_init(void);

void led_manager_led_on_for(uint32_t ms, led_type_t type);

#endif // __LED_MANAGER_H__