CONFIG_ALGORITHM="ALGORITHM_DO_NOTHING"
CONFIG_ADD_CLAIM_CERTIFICATES=y

CONFIG_PROVISIONING=y
# Enable custom AT commands to set device ID and provisioning state
CONFIG_AT_CMD_CUSTOM=y

# Log
CONFIG_LOG=y
# Set log level to info
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_ALGORITHM_LOGGING=n
CONFIG_AWS_IOT_LOG_LEVEL_DBG=n
CONFIG_MQTT_HELPER_LOG_LEVEL_DBG=n

# AT Host
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_AT_HOST_LIBRARY=y